### ISSUE TITLE
[BUG] AWS SSM put parameter Validation Exception (LIMIT) for manifest parameter value

### ISSUE THREAD

**Issue by rhwas** [awslabs/seed-farmer#499]
**Describe the bug**

We have a `seedfarmer` module which takes in over 15+ parameters from `moduleMetadata` from various modules. Our manifest file for this module contains 15+ parameters like the example below:

```yaml
- name: parameter_name
  valueFrom:
    moduleMetadata:
      group: group_name
      name: module_name
      key: DummyLambdaArn
```

`seedfarmer` stores the manifest info for this module in SSM Parameter Store under `addf/deploymentname/group/module/manifest`. For each "valueFrom" `moduleMetadata`, it creates a new entry in JSON, like below. Therefore, the number of characters quickly adds up when using 15+ parameters from `moduleMetadata`, resulting in an error when running `seedfarmer apply`.

```json
{
   "name":"parameter_name",
   "resolved_value":null,
   "value":null,
   "value_from":{
      "env_variable":null,
      "module_metadata":{
         "group":"group_name",
         "key":"DummyLambdaArn",
         "name":"module_name"
      },
      "parameter_store":null,
      "parameter_value":null,
      "secrets_manager":null
   },
   "version":null
}
```

**To Reproduce**

1. Create a new `seedfarmer` module.
2. Define enough parameters to exceed the 8192 character limit for "Advanced-tier" SSM Parameter Store values.
3. Execute `seedfarmer apply`.
4. See error below
5. Observe the value of /project/deployment/group/module/manifest in ssm parameter store for a normal module which is not exceeding the limit to see how this value should look like if working.

```
Traceback (most recent call last):
  File "/home/ruben/.pyenv/versions/ingest/bin/seedfarmer", line 8, in <module>
    sys.exit(main())
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/__main__.py", line 254, in main
    cli()
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/__main__.py", line 130, in apply
    commands.apply(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/commands/_deployment_commands.py", line 770, in apply
    deploy_deployment(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/commands/_deployment_commands.py", line 641, in deploy_deployment
    _deploy_validated_deployment(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/commands/_deployment_commands.py", line 352, in _deploy_validated_deployment
    deploy_response = list(workers.map(_exec_deploy, params))
  File "/home/ruben/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/ruben/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/ruben/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ruben/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ruben/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/commands/_deployment_commands.py", line 315, in _exec_deploy
    return _execute_deploy(**args)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/commands/_deployment_commands.py", line 186, in _execute_deploy
    du.prepare_ssm_for_deploy(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/mgmt/deploy_utils.py", line 293, in prepare_ssm_for_deploy
    mi.write_module_manifest(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/mgmt/module_info.py", line 541, in write_module_manifest
    ssm.put_parameter(name=_manifest_key(deployment, group, module), obj=data, session=session)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/seedfarmer/services/_ssm.py", line 33, in put_parameter
    client.put_parameter(
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ruben/.pyenv/versions/3.10.13/envs/ingest/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutParameter operation: The specified parameter value is too large. Advanced-tier parameters support a maximum parameter value of 8192 characters.
```

**Expected behavior**

I would expect `seedfarmer` to create a second or more SSM Parameter Store value(s) to account for manifest info larger than 8192 characters.

**Additional context**

Some background: the module in question assembles a step function. All the steps of the step function, such as Lambdas and AWS Batch, etc., are defined in separate modules which are then inputted into this module to assemble the step function. This is the reason we have so many parameters being used and therefore hitting this character limit for Advanced-tier SSM Parameter values.

**Comment by starcreep48** [comment]
This is a critical issue for us in our project. For now, the workaround has been to abbreviate all our parameters to reduce characters. We've also needed to change from using `moduleMetadata` to using hard coded `envVariables` so to also reduce characters.

For example:

```yaml
- name: parameter_name
  valueFrom:
    moduleMetadata:
      group: group_name
      name: module_name
      key: DummyLambdaArn
```

becomes:

```yaml
- name: pn
  valueFrom:
    moduleMetadata:
      group: g
      name: m
      key: DLArn
```

**Comment by dgraeber** [comment]
@starcreep48 Thanks for this feedback.   We will investigate options.

**Comment by dgraeber** [comment]
We will look to leverage the SeedKit buckets for additional storage

**Comment by rhwas** [comment]
Hi @dgraeber , thanks for the quick response. In the meantime, from your perspective and experience, what is the recommended workaround for this issue? Additionally, if you have a rough idea for when a permanent solution would be implemented, that would be great for us to know, roughly. Thanks a lot!

**Comment by dgraeber** [comment]
@rhwas Hi Ruben....we are actively looking at solutions and weighing backward-compatibility concerns.  More to come...

**Comment by dgraeber** [comment]
@rhwas the above is a stop-gap effort and should allow you to proceed (the team is evaluating unwanted side effects).   We have determined that a larger persistence solution is the proper permanent fix, but we need to identity an elegant migration strategy for existing customers.  Thus, the PR referenced is a stop-gap, but should give you 2x the storage space.

**Comment by dgraeber** [comment]
@rhwas this will be in the 3.2.0 release for seed-farmer today.  If you are updating from a version of seed-farmer that is 3.0.1 or older, be mindful of this issue with pydantic and the modification necessary:

https://github.com/awslabs/seed-farmer/issues/492
