### ISSUE TITLE
[FEATURE] Friendly errors & recommendations when requesting moduledata for non-existent modules

### ISSUE THREAD

**Issue by a13zen** [awslabs/seed-farmer#55]
**Is your feature request related to a problem? Please describe.**
When requesting moduledata for a module but using the wrong module name you get a KeyError. The error isn't intuitive that it is because you might have mistyped the module name.

```bash
Traceback (most recent call last):
  File ".venv/bin/seedfarmer", line 8, in <module>
    sys.exit(main())
  File ".venv/lib/python3.9/site-packages/seedfarmer/__main__.py", line 531, in main
    cli()
  File ".venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".venv/lib/python3.9/site-packages/seedfarmer/__main__.py", line 366, in list_module_metadata
    envs = commands.generate_export_env_params(metadata_json)
  File ".venv/lib/python3.9/site-packages/seedfarmer/commands/_parameter_commands.py", line 30, in generate_export_env_params
    for k in metadata.keys()  # type: ignore
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Describe the solution you'd like**
When requesting moduledata for a non-existent deployment/group/module

If the deployment isn't found. Output error that the deployment isn't found and list known deployments
If the group isn't found. Output error that the groups isn't found and list known groups for the deployment
If the module isn't found. Output error that the module isn't found and list known modules for the group in the deployments

**Describe alternatives you've considered**
Recommend closest deployment/module/group name similar to how click does when using a non-existent flag

**Comment by dgraeber** [comment]
I can add better context and give sample commands (that will go in the next PR).  The auto-detect and hints is something  that would take some design work (in light of multi-tenant deployments)
