### ISSUE TITLE
[FEATURE] Redirect request to specified aws entrypoint provided by localstack

### ISSUE THREAD

**Issue by koljahuang** [awslabs/seed-farmer#579]
**Is your feature request related to a problem? Please describe.**
I launch localstack container first, and configure profile correctly according offcial document of localstack. 
So i am able to run cmds like
```sh
(.venv) ➜  mynewproject git:(master) aws s3 ls --profile localstack
2024-05-11 15:14:21 cdk-hnb659fds-assets-000000000000-us-east-1
2024-05-11 15:14:50 codeseeder-mynewproject-000000000000-qrobey
```
But when I execute `seedfarmer apply manifests/deployment.yaml --env-file .env --profile localstack --dry-run`, execption raised as below:
```sh
(.venv) ➜  mynewproject git:(master) seedfarmer apply manifests/deployment.yaml --env-file .env --profile localstack --dry-run
[2024-05-11 17:28:13,516 | INFO | utils.py     :181 | MainThread ] Loading environment variables from .env
[2024-05-11 17:28:13,516 | INFO | __main__.py  :147 | MainThread ] Apply request with manifest manifests/deployment.yaml
 ***   This is a dry-run...NO ACTIONS WILL BE TAKEN  ***
[2024-05-11 17:28:13,518 | INFO | session_manager.py:178 | MainThread ] Creating toolchain session
[2024-05-11 17:28:15,499 | ERROR | _service_utils.py:120 | MainThread ] ERROR: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
Please make sure you have a valid AWS Session
Traceback (most recent call last):
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/bin/seedfarmer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/__main__.py", line 295, in main
    cli()
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/__main__.py", line 151, in apply
    commands.apply(
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 640, in apply
    _, _, partition = get_sts_identity_info(session=session_manager.toolchain_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/services/_service_utils.py", line 128, in get_sts_identity_info
    sts_info = _call_sts(session=session, profile=profile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/services/_service_utils.py", line 124, in _call_sts
    raise e
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seedfarmer/services/_service_utils.py", line 111, in _call_sts
    return cast(Dict[str, Any], boto3_client(service_name="sts", session=session).get_caller_identity())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```

**Describe the solution you'd like**
I have posted a pr to seed-famer project and similar pr to aws-codeseeder project via accepting env variable as workaound to avoid this exception. Theoretically there should not be this error because the profile parameter has been exposed and will be referenced when creating a session. However, I saw that many session = SessionManager().get_or_create() in the source code did not pass in this parameter. Maybe This causes the session to be unable to obtain the endpoint when creating the boto3 client.
I hope this profile parameter works well.

Thanks very much

**Comment by koljahuang** [comment]
> @koljahuang Thanks for this info. I will investigate... Also, can you run with the `--debug` flag? This will add extra information to the logging. For example, on the apply I can see that the profile is passed to the session `getOrCreate` (line 631 of deployment_commands.py) so the profile is indeed being passed on that command call. But the debug will indicate more metadata....
> 
> You may see something like:
> 
> ```
> [2024-05-11 08:59:22,652 | DEBUG | session_manager.py:188 | MainThread ] Creating a local session with the following info passed in:
>                       region_name = us-east-1
>                       profile_name = dgraeber
>                       project_name = idf
>                       qualifier = None
> 
>                       NOTE: if not set here, the active environment parameters are used to create a new AWS session
>                             much like how the AWS CLI operates.
> ```
> 
> Looking further at the stack trace, the error is occurring when we try to call the sts_identity_info with the session that is created (line 640) -- that fails due to the endpoint issue. The sessions are being created with the proper profile.
> 
> Overriding the endpoint url en-mass with an env parameter will violate our security contracts.

Hi, pls see details as below 👇
```sh
(.venv) ➜  mynewproject git:(master) seedfarmer apply manifests/deployment.yaml --env-file .env --profile localstack --dry-run --debug
[2024-05-12 10:37:11,793 | INFO | utils.py     :181 | MainThread ] Loading environment variables from .env
[2024-05-12 10:37:11,794 | DEBUG | utils.py     :187 | MainThread ] Loaded environment variables: {'PRIMARY_ACCOUNT': '000000000000'}
[2024-05-12 10:37:11,794 | INFO | __main__.py  :147 | MainThread ] Apply request with manifest manifests/deployment.yaml
 ***   This is a dry-run...NO ACTIONS WILL BE TAKEN  ***
[2024-05-12 10:37:11,796 | DEBUG | _deployment_commands.py:628 | MainThread ] {'name': 'example', 'name_generator': None, 'toolchain_region': 'us-east-1', 'groups': [{'name': 'mygroup', 'path': 'manifests/mymodule.yaml', 'modules': [], 'concurrency': None}], 'description': None, 'target_account_mappings': [{'alias': 'primary', 'account_id': {'value_from': {'module_metadata': None, 'env_variable': 'PRIMARY_ACCOUNT', 'parameter_store': None, 'secrets_manager': None, 'parameter_value': None}}, 'default': True, 'parameters_global': {}, 'region_mappings': [{'region': 'us-east-1', 'default': True, 'parameters_regional': {}, 'network': None, 'codebuild_image': None, 'npm_mirror': None, 'pypi_mirror': None, 'pypi_mirror_secret': None, 'seedkit_metadata': None}], 'codebuild_image': None, 'npm_mirror': None, 'pypi_mirror': None, 'pypi_mirror_secret': None}], 'force_dependency_redeploy': False}
[2024-05-12 10:37:11,796 | INFO | session_manager.py:178 | MainThread ] Creating toolchain session
[2024-05-12 10:37:11,796 | DEBUG | session_manager.py:188 | MainThread ] Creating a local session with the following info passed in:
                      region_name = None
                      profile_name = localstack
                      project_name = mynewproject
                      qualifier = None

                      NOTE: if not set here, the active environment parameters are used to create a new AWS session
                            much like how the AWS CLI operates.

[2024-05-12 10:37:11,801 | DEBUG | _service_utils.py: 33 | MainThread ] Proxies Configured: {'http': None, 'https': None}
[2024-05-12 10:37:11,909 | DEBUG | session_manager.py:207 | MainThread ] The active user session will assume the toolchain role
                      arn = arn:aws:iam::000000000000:role/seedfarmer-mynewproject-toolchain-role
                      toolchain_region = us-east-1

[2024-05-12 10:37:11,909 | DEBUG | _service_utils.py: 33 | MainThread ] Proxies Configured: {'http': None, 'https': None}
[2024-05-12 10:37:11,926 | DEBUG | _service_utils.py: 33 | MainThread ] Proxies Configured: {'http': None, 'https': None}
[2024-05-12 10:37:13,325 | ERROR | _service_utils.py:120 | MainThread ] ERROR: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
Please make sure you have a valid AWS Session
```

**Comment by koljahuang** [comment]
The issure will violate seed-farmer security contract.
